---
title: '`r paste("Pollen diagrams for", params$region$name)`'
author: "Richard J. Telford"
date: "April 17, 2018"
geometry: margin=2cm
output: 
  pdf_document
documentclass: article
classoption: a4paper
params:
  region: !r data_frame(name = "Global", lonW = -180.1, latS = 90, lonE = 180.1, latN = 90)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
```


```{r load_packages, cache=FALSE}
library("tidyverse")

source("R/make_stratplot.R")
source("R/make_summary_plot.R")
```

```{r load_data, warning = FALSE}
mp <- map_data("world")
detach("package:maps")

region <- params$region

load("data/pollen.Rdata") 

sites_meta <- sites_meta %>% 
  filter(long >= region$lonW,
         long <  region$lonE,
         lat  >= region$latS,
         lat  <  region$latN)
```

## Basic maps

```{r site_map}
g <- sites_meta %>% 
ggplot(aes(x = long, y = lat, colour = length)) +
  geom_map(data = mp, map = mp, aes(map_id = region), inherit.aes = FALSE, fill = "grey80") +
  geom_rect(data = region, 
    mapping = aes(xmin = lonW, xmax = lonE, ymin = latS, ymax = latN), colour = "red", fill = NA, inherit.aes = FALSE) +
  geom_point() +
  coord_quickmap() +
  scale_y_continuous(expand = c(0.01, 0)) + 
  scale_x_continuous(expand = c(0.01, 0)) 

g
```

###Issues

- Several sites lack chronologies
- Many sites are on uncalibrated radiocarbon age-models 

```{r depo_map}
g %+% (sites_meta %>% filter(length == "Most Holocene")) +
         aes(colour = DepEnvt.4)
```
 
This is coarsest classification of depositional environments. 

Forest hollows are not a distinct depositional environment type.


## Pollen diagrams

```{r subset}
sites_meta <- sites_meta %>% 
  filter(length == "Most Holocene")
```

```{r spikes, warning = FALSE}
combinedtaxonomy <- pollen_data %>% map_df("taxon.list") %>% distinct() %>% as_tibble()

spike_variables <- combinedtaxonomy %>% 
  filter(ecological.group == "LABO") %>% 
  select(-ecological.group, -taxon.group, -variable.context) %>% 
  filter(!variable.element  %in% c("wet mass", "volume examined", "volume", "total", "pollen/spore", "number", "mounted volume", "dry mass", "dry mass examined"), 
         !taxon.name %in% c("Author's pollen sum", "Sample quantity", "Number of lines", "Transects across slide", "Synthetic depth"))
    
spikes <- c(spike_variables$taxon.name, spike_variables$alias) 
```


```{r plot_figure, results = 'asis', warning = FALSE, message = FALSE, out.extra=c("angle=0", "angle=90"), out.width = c("400px", "600px"), out.height=c("400px", "500px"), cache = FALSE}
for(i in sites_meta$dataset.id[1:5]) {
  x <- sites_meta %>% 
    filter(dataset.id == i) %>% 
    select(dataset.id, site.name, long, lat, elev, description, age_min, age_max, res, DepEnvt)
  
  #print site name and meta data
  cat("\n\n##", x$site.name, "\n\n")
  knitr::kable(x %>% select(-description), digits = 2) %>% paste(collapse = "\n") %>% cat()
  cat("\n\n", x$description, "\n\n")
  
  
  #has charcoal
  taxon_names <- pollen_data[[as.character(i)]]$taxon.list
  if(any(taxon_names$ecological.group == "CHAR")){
    cat("Charcoal counts in pollen data = TRUE\n\n")
  } else{
    cat("Charcoal counts in pollen data = FALSE\n\n")
  }
  
  #has spike
  lab.names <- pollen_data[[as.character(i)]]$lab.data %>% names
  spi <- intersect(lab.names, spikes)
  if(length(spi) > 0){ 
    cat("Spike variables", spi, "\n\n")
  } else{
    cat("No declared spike\n\n")
  }
  
  #summary diagram
  p <- make_summary_plot(
    pollen_data[[as.character(i)]], yaxis = "depth", group = wanted)
  print(p)
  
   cat("\n\n\\pagebreak\n\n")
  
  #need to truncate age
  make_stratplot(
    pollen_data[[as.character(i)]], yaxis = "depth", y.rev = TRUE, 
    method = "percent", group = wanted,
    scale.percent = TRUE,
    exag = TRUE, exag.mult  = 10, 
    plot.poly = TRUE, col.poly = "grey40", 
    srt.xlabel = 50, cex.xlabel = .6, 
    cex.ylabel=.7, cex.yaxis=0.6, cex.axis=.6, 
    yTop  = 0.75, xRight = .95)
  
  cat("\\pagebreak")
  }
```
